credentials:
  usernames:
    # Seu usu√°rio com a nova senha master criptografada
    samuel:
      email: samukatas@gmail.com
      name: Samuel
      password: '$2b$12$RG1Xoh//J7TgX3VnwsNhzub8KBAj29qm8R6uZPx9CrZaBeWDJ8Nry' # Senha criptografada

    filipe:
      email: filipe.guimaraes@icloud.com
      name: Filipe
      password: '$2b$12$RG1Xoh//J7TgX3VnwsNhzub8KBAj29qm8R6uZPx9CrZaBeWDJ8Nry' # Senha criptografada
            
cookie:
  expiry_days: 30
  key: alguma_chave_secreta_aleatoria
  name: algum_nome_de_cookie_aleatorio